import React, { useState, useEffect } from 'react';
import axios from 'axios';
import './App.css';
// Bootstrap Components
import Col from 'react-bootstrap/Col';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Head from 'next/head'
import Navbar from '@/components/Navbar'

export default function Home() {
  const [weatherDays, setWeatherDays] = useState([]);
	const [updated, setUpdated] = useState(false);
	const [city, setCity] = useState({});
	const [travelDays, setTravelDays] = useState([]);

	const callApi = () => {
		const axios = require('axios');

		const options = {
			method: 'GET',
			url: 'https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/recipes/complexSearch',
			params: {
				query: 'pasta',
				cuisine: 'italian',
				excludeCuisine: 'greek',
				diet: 'vegetarian',
				intolerances: 'gluten',
				equipment: 'pan',
				includeIngredients: 'tomato,cheese',
				excludeIngredients: 'eggs',
				type: 'main course',
				instructionsRequired: 'true',
				fillIngredients: 'false',
				addRecipeInformation: 'false',
				titleMatch: 'Crock Pot',
				maxReadyTime: '20',
				ignorePantry: 'true',
				sort: 'calories',
				sortDirection: 'asc',
				offset: '0',
				number: '10',
				limitLicense: 'false',
				ranking: '2',
			},
			headers: {
				'X-RapidAPI-Key': process.env.RECIPEAPI_KEY,
				'X-RapidAPI-Host': process.env.RECIPEAPI_HOST,
			},
		};

		axios
			.request(options)
			.then(function (response) {
				console.log(response.data);
			})
			.catch(function (error) {
				console.error(error);
			});
	};

	const getWeather = (lat, lon) => {
		lat
			? axios
					.get(`https://api.weather.gov/points/${lat},${lon}`)
					.then((res) => {
						axios.get(res.data.properties.forecast).then((weatherRes) => {
							const weatherData = weatherRes.data.properties.periods;
							setWeatherDays(weatherData);
						});
					})
			: console.log('Hey');
	};

	const formSubmit = (e) => {
		e.preventDefault();
		getCoord(e.target.city.value, e.target.state.value);
		setUpdated(!updated);
	};

	const getCoord = (city, state) => {
		axios
			.get(
				`https://api.tomtom.com/search/2/geocode/${city} ${state}.json?key=IvZAJEwT4tG2uDSoidDzUFkkuWgX8L5J`
			)
			.then((res) => {
				setCity(res.data.results[0].address);
				let lat = res.data.results[0].position.lat;
				let lon = res.data.results[0].position.lon;
				console.log(lat);
				getWeather(lat, lon);
			});
	};

	useEffect(() => {
		getWeather();
	}, [updated]);

  return (
		<>
			<Head>
				<title>Meal Planner</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
			</Head>
			<Container>
				<TravelCard
					travelDays={travelDays}
					setTravelDays={setTravelDays}
					callApi={callApi}
				/>
				<h1>Weather Travel Guide</h1>
				<form onSubmit={formSubmit}>
					City: <input type='text' name='city' />
					State: <input type='text' name='state' />
					<input type='submit' value='Submit' />
				</form>
				<Row>
					{weatherDays
						? weatherDays.map((day, i) => {
								if (i % 2 === 0) {
									return (
										<Row key={i}>
											<Col sm={6} md={4}>
												<DayWeather
													day={day}
													city={city}
													travelDays={travelDays}
													setTravelDays={setTravelDays}
													callApi={callApi}
												/>
											</Col>
											{weatherDays[i + 1] && (
												<Col sm={6} md={4}>
													<DayWeather
														day={weatherDays[i + 1]}
														city={city}
														travelDays={travelDays}
														setTravelDays={setTravelDays}
														callApi={callApi}
													/>
												</Col>
											)}
										</Row>
									);
								}
								return null;
						})
						: ' '}
				</Row>
			</Container>
		</>
	);
}